### PR TITLE
Add YOLOv10 support

### PR DESCRIPTION
**Pull request by sokovninn**
This PR includes:

- Added Yolov10 export support (export to ONNX and RVC2 works, RVC3 doesn't)

What is missing:

- ultralytics version is not updated since yolov10 PR is not merged yet (https://github.com/ultralytics/ultralytics/pull/13113)
- unit tests

### CODE REVIEW

**Comment by sokovninn** [comment]
@HonzaCuhel please take a look. Btw, I wasn't sure how to modify store.js since some version (yolov8) are missing there.

**Comment by sokovninn** [comment]
@HonzaCuhel sorry for the late reply. Yes, during the compilation with the openvino compile_tool.

**Comment by HonzaCuhel** [comment]
@sokovninn Can you send me the error what does it say?

Could you please then update the warning saying that the YOLOv10 RVC3 doesn't work, you can use [this](https://github.com/luxonis/tools/blob/yolov10/client/src/App.js#L95-L99) and just rewrite the warning message.

**Review by HonzaCuhel — APPROVED** [review]

**Comment by sokovninn** [comment]
@HonzaCuhel could you please run unit tests with the updated ultralytics version and added yolov10?
CC: @tersekmatija

**Review by HonzaCuhel — APPROVED** [review]
LGTM, ran the unittests and they work for RVC2. Gonna look for the source of the issue for RVC3.

**Comment by HonzaCuhel** [comment]
@sokovninn, @tersekmatija Regarding the RVC3, I investigated the error message, but as it doesn't contain almost any information, I didn't get far, I also tried to compile the model on the Prague's KeemBay device with a slightly different version of OpenVINO, but that also didn't work. I didn't find any relevant info on internet either.

So, could you please then @sokovninn add the warning saying that the YOLOv10 RVC3 doesn't work, you can use [this](https://github.com/luxonis/tools/blob/yolov10/client/src/App.js#L95-L99) and just rewrite the warning message? I didn't see it in the App.js file, but correct me if I'm mistaken.

**Comment by sokovninn** [comment]
@HonzaCuhel thanks for the review, I've added the warning. Should I merge it or you?

**Comment by HonzaCuhel** [comment]
It doesn't matter, I'll merge it.

**Pull request merged**
